// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ddd/controller"
	"ddd/infrastructure/ioc"
	"ddd/repo"
	"ddd/repo/cache"
	"ddd/repo/dao"
	"ddd/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

//go:generate wire
func InitWeb() (*gin.Engine, error) {
	v := ioc.InitMiddlewares()
	sugaredLogger := ioc.InitZap()
	db := ioc.InitMysql()
	userDao := dao.NewUserDao(sugaredLogger, db)
	cmdable := ioc.InitRedis()
	userCache := cache.NewUserCache(sugaredLogger, cmdable)
	userRepo := repo.NewUserRepo(sugaredLogger, userDao, userCache)
	userService := service.NewUserService(sugaredLogger, userRepo)
	userController := controller.NewUserController(sugaredLogger, userService)
	engine := ioc.InitGin(v, userController)
	return engine, nil
}
